import datetime

# border-box
# font
FONT_TYPE = "HarmonyOS_Sans_SC_Regular.ttf"
FONT_SIZE = 31
# margin
MARGIN_TOP = 10
MARGIN_RIGHT = 10
MARGIN_BUTTOM = 40
MARGIN_LEFT = 10
# topbar
TOPBAR_Y = MARGIN_TOP
TOPBAR_HEIGHT = 40
TOPBAR_FONT_SIZE = 20
WEEKORDER_ANCHOR = (985, 20)
# weekbar
WEEKBAR_Y = TOPBAR_Y + TOPBAR_HEIGHT
WEEKBAR_HEIGHT = 53
WEEKBAR_FONT_SIZE = 20
DOW_ANCHOR = (56, 8)
DATE_ANCHOR = (52, 29)
# course
COURSE_Y = WEEKBAR_Y + WEEKBAR_HEIGHT
COURSE_HEIGHT = 162
COURSE_WIDTH = 150
COURSE_MARGIN = 3
COURSE_RADIUS = 10
COURSE_NAME_ANCHOR = (10, 10)
COURSE_ROOM_ANCHOR = (10, -80)
# 三行 (10, -110)
# buttom
# TODO 想想 bottom 写点啥呢
BUTTOM_Y = COURSE_Y + COURSE_HEIGHT * 13
BOTTOM_HEIGHT = 0
# base
BASE_HEIGHT = BUTTOM_Y + BOTTOM_HEIGHT + MARGIN_BUTTOM
BASE_WIDTH = MARGIN_LEFT + MARGIN_RIGHT + COURSE_WIDTH * 7
# time
DAY_ANCHOR = datetime.datetime.strptime("2021-09-05", "%Y-%m-%d")
WEEK_SPAN = datetime.timedelta(days=7)
DAY_SPAN = datetime.timedelta(days=1)
COURSE_PIC_SAVE_PATH = "./src/jpg/"
